server:
  port: 8082
s3:
  endpointUrl: ${S3_ENDPOINT_URL}
  accessKeyId: ${S3_ACCESS_KEY_ID}
  secretKey: ${S3_SECRET_KEY}
  bucketName: ${S3_BUCKET_NAME}
  region: ${S3_REGION}

spring:
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
  data:
    mongodb:
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      host: ${DB_HOST}
      authentication-database: ${DB_AUTH_DB}
      database: ${DB_DB_NAME}
