#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

for FOLDER in $(ls -d */ | grep -v "node_modules")
do

  cd $FOLDER;

  if test -f "package.json"; then
    npm run precommit
  fi;

  cd ..;

done;
