spring:
  jpa:
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  data:
    elasticsearch:
      repositories:
        enabled: true
    mongodb:
      username: mongo
      password: root
      host: localhost
      authentication-database: admin
      database: shotcutter
  elasticsearch:
    rest:
      uris:
        - http://localhost:9200
tmdb:
  api:
    key: ${TMDB_API_KEY}
  integration:
    init: ${TMDB_INTEGRATION_INIT:false}
    delay: 10000
